name: Ubuntu Default Build Test

on: [push, pull_request]

jobs:
  ubuntu-default-build-test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: List added files
      run: git --no-pager diff --name-only "$(git rev-parse --verify origin/master 2> /dev/null)" HEAD
    -
      name: Ubuntu Default Build Test
      run: |
        sudo apt-get install build-essential git libwebsockets-dev pkg-config \
        zlib1g-dev libnl-3-dev libnl-genl-3-dev libcap-dev libpcap-dev \
        libnm-dev libdw-dev libsqlite3-dev \
        libsensors-dev libusb-1.0-0-dev \
        python3 python3-setuptools python3-requests \
        python3-numpy python3-serial python3-usb python3-dev python3-websockets \
        libubertooth-dev libbtbb-dev libmosquitto-dev librtlsdr-dev
        sudo apt install rtl-433
        ./configure
        make -j$(nproc)
        sudo make suidinstall
